### ISSUE TITLE
Normalize Dimensional Scores

### ISSUE THREAD

**Issue by aliforgetti** [dsi-principles-prog/midterm-aliforgetti#1]
**Name of Function:** norm_by_var
**Description of Function:**
The ranges of dimensional scores (extraversion, neuroticism, openness, agreeableness, etc) are all different and they thus need to be normalized so they are within the range of 0 to 1. 

**Property of function:**
Input: dataframe, columns of dimensional scores
Output: new columns with suffix “_norm” next to them. For example , extraversion will have a new column called “extraversion_norm” related to it. 

**Formula for normalization is given by:**
a = set of values
x = a value in a

f(x) = x - min(a)/(max(a)-min(a))

This should return the normalized value of x in a. It should be a value within 0 and 1. 

For our case, x would be each score and min(a) would be minimum score in the whole column of that score.  You would be manipulating a whole column here.

**Verifying if it worked:**
You should check if the values in the new column are within the bounds of 0 and 1. 

**Input Columns:**
extraversion = 14  
neuroticism  = -1	
agreeableness = 22 
conscientiousness = 23
		   				
**Output Columns:**
extraversion_norm = 0.850 
neuroticism_norm = 0.025  
agreeableness_norm = 0.900  
conscientiousness_norm = 0.925	

**Note:** Please make sure to make new columns for the normalized values. We want to make sure we keep original dimensional scores in case we want to use them for something else.

**Comment by adeniro21** [comment]
I have added the norm_by_var function to normalize the dimensional scores.
